debugging the proxy class, setting up IDEA

diff --git a/tester/tool🖉/make b/tester/tool🖉/make
--- a/tester/tool🖉/make
+++ b/tester/tool🖉/make
@@ -3,29 +3,37 @@ script_afp=$(realpath "${BASH_SOURCE[0]}")
 
 # input guards
 
-  env_must_be="tester/tool🖉/env"
-  if [ "$ENV" != "$env_must_be" ]; then
-    echo "$(script_fp):: error: must be run in the $env_must_be environment"
-    exit 1
-  fi
+env_must_be="tester/tool🖉/env"
+if [ "$ENV" != "$env_must_be" ]; then
+  echo "$(script_fp):: error: must be run in the $env_must_be environment"
+  exit 1
+fi
 
 echo "Compiling files..."
 
-  set -x
-  cd $REPO_HOME/tester
-  javac -g -d scratchpad javac🖉/*.java
-  set +x 
+set -x
+cd $REPO_HOME/tester
+
+# Get the list of tests to compile
+# wrapper is a space-separated list
+wrapper_list=$(test_list)
+
+# make class files
+for file in $wrapper_list; do
+  javac -g -d scratchpad "javac🖉/$file.java"
+done
+set +x 
 
 echo "Creating bash wrappers..."
-  mkdir -p bash
-  # wrapper is a space separated list
-  wrapper=$(bash_wrapper_list)
-  for file in $wrapper;do
-    cat > bash/$file << EOL
+mkdir -p bash
+
+# make shell call wrappers
+for file in $wrapper_list; do
+  cat > bash/$file << EOL
 #!/bin/env bash
 java $file
 EOL
-    chmod +x bash/$file
+  chmod +x bash/$file
   done
 
 echo "$(script_fp) done."
